name: nsyte
base: core22
version: '0.7.0'
summary: Command-line tool for publishing websites to nostr and Blossom servers
description: |
  nsyte is a command-line tool for publishing websites to nostr and Blossom servers.
  It enables decentralized, censorship-resistant website hosting.

  Features:
  - Upload websites to multiple Blossom servers
  - Publish metadata to nostr relays
  - Support for NIP-46 bunkers for secure key management
  - CI/CD integration support
  - File ignore patterns (.nsite-ignore)
  - Interactive and non-interactive modes

grade: stable
confinement: strict

architectures:
  - build-on: amd64

apps:
  nsyte:
    command: bin/nsyte
    plugs:
      - network
      - home
      - removable-media

parts:
  nsyte:
    plugin: dump
    source: https://github.com/sandwichfarm/nsyte/releases/download/v0.7.0/nsyte-linux
    source-type: file
    source-checksum: sha256/PLACEHOLDER_SHA256
    organize:
      nsyte-linux: bin/nsyte
    stage:
      - bin/nsyte
    override-stage: |
      craftctl default
      chmod +x $CRAFT_STAGE/bin/nsyte